# -*- coding: utf-8 -*-
"""packages.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J4uPHJ86P3iGPP79FJxSEQfCSqwcUEiu
"""
# from clm_model_tuning import *

# def packages():
#   import transformers
#   from transformers import AutoModelForCausalLM
#   from huggingface_hub import HfApi
#   print(transformers.__version__)
#   print('x')


# if __name__ == '__main__':
#     packages()



from huggingface_hub import HfApi
api = HfApi()
api.upload_folder(
    folder_path="/content/clm_model_tuning/Test-gpt2-BittensorTuned",  #The model weights folder
    path_in_repo="",      #Path to the Files Location, Files.
    repo_id="asifhugs/Testing",    #HuggingFace Hub Repo ID
    repo_type="model",
    #ignore_patterns="**/logs/*.txt",
)
print('Pushing the is Done!')



# output_dir = 'Test-gpt2-BittensorTuned'

# from transformers import AutoModelForCausalLM
# def ModelPush():
#     model = AutoModelForCausalLM.from_pretrained('Test-gpt2-BittensorTuned')
#     model.push_to_hub('Test-gpt2-BittensorTuned')

# if __name__ == '__main__':
#     ModelPush()

    



